### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by HonestPrivacy** [r-selfhosted-wiki/wiki#1]
Hello!

Would you be able to add a license to the project?

Without adding a license, we would need to assume the project is All Rights Reserved. Without your permission, we would not be able to modify the documentation or use it.

https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license

Other projects similar to this use the Creative Commons licenses:

[Linode Documentation](https://www.linode.com/lp/write-for-linode/) is provided under the [CC BY-ND 4.0](https://creativecommons.org/licenses/by-nd/4.0/) license.

[Digital Ocean Tutorials](https://www.digitalocean.com/community/tutorials) are provided under the [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license.

**Comment by kmorton1988** [comment]
~~Do you have a recommended license for this kind of project?~~

Nevermind, I can read, I promise. I'll add a license soon.

**Comment by kmorton1988** [comment]
Creative Commons Zero license chosen and applied.
