### ISSUE TITLE
Best Place for a Suggested Topic List

### ISSUE THREAD

**Issue by simbarb** [r-selfhosted-wiki/wiki#6]
Hi there,

Looking forward to seeing this grow!

It would be great to have a list of topics / subject matter that we would like to see covered. It may make it easier for contributers to come along and simply pick a topic from the list and start writing.

That said, I'm not sure if they should be their GitHub issues or tracked elsewhere.

**Comment by jacebenson** [comment]
I'm a fan of using Github Issues to track this kind of stuff.  You can use tags to seperate out issues from the site vs content issues.

**Comment by kmorton1988** [comment]
I'm thinking I'm in line with what @jacebenson offered. Create an Issue for it, and tag it with "Content Issue" and we can start building a list of desired topics.
